version: '3'
services:
  database:
    image: postgres:10.3-alpine
    ports:
        - "127.0.0.1:5432:5432"
    # do not change! This data is hard coded in the pgadmin database file, to auto configure pg admin to access the postgresdb
    container_name: db-lab-postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment: 
      # do not change the credencials below, due to the same reson as above. 
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadminpassword
  pgadmin4:
    build: ./pgadmin/
    ports:
        - "127.0.0.1:5050:5050"
    container_name: db-lab-pgadmin
    environment: 
      # do not change the credencials below, due to the same reson as above. 
      - DEFAULT_USER=user
      - DEFAULT_PASSWORD=secretpassword

volumes:
    pgdata:
  
